### ISSUE TITLE
ngenicpy 0.2.1 has requirement httpx<0.13,>=0.12, but homeassistant now requires httpx 0.16.1

### ISSUE THREAD

**Issue by bictorv** [sfalkman/ngenicpy#6]
Is there a known problem with later httpx versions? Can I help?

**Comment by sfalkman** [comment]
Hey,
It was recommended by httpx to pin dependencies to 0.12.*, although they are now recommending 0.16.*

Is this causing issues in homeassistant?

**Comment by bictorv** [comment]
I don't recall more issues right now than the warning/confusion when I upgraded homeassistant, then ngenicpy, and then homeassistant again.

**Comment by sfalkman** [comment]
I've also updated the homeassistant component. Could you please retest to see if you still get the warnings?

**Comment by bictorv** [comment]
Oh dear... in homeassistant 0.117.6:

```
Nov 13 13:28:17 pi3 hass[26493]: 2020-11-13 13:28:16 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up ngenic platform for sensor
Nov 13 13:28:17 pi3 hass[26493]: Traceback (most recent call last):
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/httpx/_exceptions.py", line 326, in map_exceptions
Nov 13 13:28:17 pi3 hass[26493]:     yield
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/httpx/_client.py", line 1507, in _send_single_request
Nov 13 13:28:17 pi3 hass[26493]:     ext={"timeout": timeout.as_dict()},
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/httpcore/_async/connection_pool.py", line 219, in arequest
Nov 13 13:28:17 pi3 hass[26493]:     method, url, headers=headers, stream=stream, ext=ext
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/httpcore/_async/connection.py", line 92, in arequest
Nov 13 13:28:17 pi3 hass[26493]:     self.socket = await self._open_socket(timeout)
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/httpcore/_async/connection.py", line 123, in _open_socket
Nov 13 13:28:17 pi3 hass[26493]:     local_address=self.local_address,
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/httpcore/_backends/auto.py", line 45, in open_tcp_stream
Nov 13 13:28:17 pi3 hass[26493]:     hostname, port, ssl_context, timeout, local_address=local_address
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/httpcore/_backends/asyncio.py", line 244, in open_tcp_stream
Nov 13 13:28:17 pi3 hass[26493]:     stream_reader=stream_reader, stream_writer=stream_writer
Nov 13 13:28:17 pi3 hass[26493]:   File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
Nov 13 13:28:17 pi3 hass[26493]:     self.gen.throw(type, value, traceback)
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
Nov 13 13:28:17 pi3 hass[26493]:     raise to_exc(exc) from None
Nov 13 13:28:17 pi3 hass[26493]: httpcore.ConnectTimeout
Nov 13 13:28:17 pi3 hass[26493]: The above exception was the direct cause of the following exception:
Nov 13 13:28:17 pi3 hass[26493]: Traceback (most recent call last):
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/ngenicpy/models/base.py", line 170, in _async_request
Nov 13 13:28:17 pi3 hass[26493]:     r = await request_method(*args, **kwargs)
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/httpx/_client.py", line 1556, in get
Nov 13 13:28:17 pi3 hass[26493]:     timeout=timeout,
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/httpx/_client.py", line 1372, in request
Nov 13 13:28:17 pi3 hass[26493]:     request, auth=auth, allow_redirects=allow_redirects, timeout=timeout
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/httpx/_client.py", line 1411, in send
Nov 13 13:28:17 pi3 hass[26493]:     history=[],
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/httpx/_client.py", line 1448, in _send_handling_auth
Nov 13 13:28:17 pi3 hass[26493]:     history=history,
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/httpx/_client.py", line 1476, in _send_handling_redirects
Nov 13 13:28:17 pi3 hass[26493]:     response = await self._send_single_request(request, timeout)
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/httpx/_client.py", line 1507, in _send_single_request
Nov 13 13:28:17 pi3 hass[26493]:     ext={"timeout": timeout.as_dict()},
Nov 13 13:28:17 pi3 hass[26493]:   File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
Nov 13 13:28:17 pi3 hass[26493]:     self.gen.throw(type, value, traceback)
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/httpx/_exceptions.py", line 343, in map_exceptions
Nov 13 13:28:17 pi3 hass[26493]:     raise mapped_exc(message, **kwargs) from exc  # type: ignore
Nov 13 13:28:17 pi3 hass[26493]: httpx.ConnectTimeout
Nov 13 13:28:17 pi3 hass[26493]: During handling of the above exception, another exception occurred:
Nov 13 13:28:17 pi3 hass[26493]: Traceback (most recent call last):
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 197, in _async_setup_platform
Nov 13 13:28:17 pi3 hass[26493]:     await asyncio.shield(task)
Nov 13 13:28:17 pi3 hass[26493]:   File "/home/homeassistant/.homeassistant/custom_components/ngenic/sensor.py", line 117, in async_setup_entry
Nov 13 13:28:17 pi3 hass[26493]:     for tune in await ngenic.async_tunes():
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/ngenicpy/ngenic.py", line 39, in async_tunes
Nov 13 13:28:17 pi3 hass[26493]:     return await self._async_parse_new_instance(url, Tune)
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/ngenicpy/models/base.py", line 123, in _async_parse_new_instance
Nov 13 13:28:17 pi3 hass[26493]:     ret_json = self._parse(await self._async_get(url))
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/ngenicpy/models/base.py", line 236, in _async_get
Nov 13 13:28:17 pi3 hass[26493]:     **kwargs)
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/ngenicpy/models/base.py", line 177, in _async_request
Nov 13 13:28:17 pi3 hass[26493]:     raise ClientException(self._get_error("A request exception occurred", r, parent_ex=exc))
```

**Comment by bictorv** [comment]
followed by
```
 2020-11-13 13:28:16 ERROR (SyncWorker_51) [homeassistant] Error doing job: Task was destroyed but it is pending!
Nov 13 13:28:17 pi3 hass[26493]: 2020-11-13 13:28:16 ERROR (MainThread) [homeassistant.components.climate] Error while setting up ngenic platform for climate
Nov 13 13:28:17 pi3 hass[26493]: Traceback (most recent call last):
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/httpx/_exceptions.py", line 326, in map_exceptions
Nov 13 13:28:17 pi3 hass[26493]:     yield
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/httpx/_client.py", line 1507, in _send_single_request
Nov 13 13:28:17 pi3 hass[26493]:     ext={"timeout": timeout.as_dict()},
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/httpcore/_async/connection_pool.py", line 219, in arequest
Nov 13 13:28:17 pi3 hass[26493]:     method, url, headers=headers, stream=stream, ext=ext
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/httpcore/_async/connection.py", line 92, in arequest
Nov 13 13:28:17 pi3 hass[26493]:     self.socket = await self._open_socket(timeout)
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/httpcore/_async/connection.py", line 123, in _open_socket
Nov 13 13:28:17 pi3 hass[26493]:     local_address=self.local_address,
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/httpcore/_backends/auto.py", line 45, in open_tcp_stream
Nov 13 13:28:17 pi3 hass[26493]:     hostname, port, ssl_context, timeout, local_address=local_address
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/httpcore/_backends/asyncio.py", line 244, in open_tcp_stream
Nov 13 13:28:17 pi3 hass[26493]:     stream_reader=stream_reader, stream_writer=stream_writer
Nov 13 13:28:17 pi3 hass[26493]:   File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
Nov 13 13:28:17 pi3 hass[26493]:     self.gen.throw(type, value, traceback)
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
Nov 13 13:28:17 pi3 hass[26493]:     raise to_exc(exc) from None
Nov 13 13:28:17 pi3 hass[26493]: httpcore.ConnectTimeout
Nov 13 13:28:17 pi3 hass[26493]: The above exception was the direct cause of the following exception:
Nov 13 13:28:17 pi3 hass[26493]: Traceback (most recent call last):
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/ngenicpy/models/base.py", line 170, in _async_request
Nov 13 13:28:17 pi3 hass[26493]:     r = await request_method(*args, **kwargs)
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/httpx/_client.py", line 1556, in get
Nov 13 13:28:17 pi3 hass[26493]:     timeout=timeout,
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/httpx/_client.py", line 1372, in request
Nov 13 13:28:17 pi3 hass[26493]:     request, auth=auth, allow_redirects=allow_redirects, timeout=timeout
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/httpx/_client.py", line 1411, in send
Nov 13 13:28:17 pi3 hass[26493]:     history=[],
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/httpx/_client.py", line 1448, in _send_handling_auth
Nov 13 13:28:17 pi3 hass[26493]:     history=history,
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/httpx/_client.py", line 1476, in _send_handling_redirects
Nov 13 13:28:17 pi3 hass[26493]:     response = await self._send_single_request(request, timeout)
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/httpx/_client.py", line 1507, in _send_single_request
Nov 13 13:28:17 pi3 hass[26493]:     ext={"timeout": timeout.as_dict()},
Nov 13 13:28:17 pi3 hass[26493]:   File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
Nov 13 13:28:17 pi3 hass[26493]:     self.gen.throw(type, value, traceback)
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/httpx/_exceptions.py", line 343, in map_exceptions
Nov 13 13:28:17 pi3 hass[26493]:     raise mapped_exc(message, **kwargs) from exc  # type: ignore
Nov 13 13:28:17 pi3 hass[26493]: httpx.ConnectTimeout
Nov 13 13:28:17 pi3 hass[26493]: During handling of the above exception, another exception occurred:
Nov 13 13:28:17 pi3 hass[26493]: Traceback (most recent call last):
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 197, in _async_setup_platform
Nov 13 13:28:17 pi3 hass[26493]:     await asyncio.shield(task)
Nov 13 13:28:17 pi3 hass[26493]:   File "/home/homeassistant/.homeassistant/custom_components/ngenic/climate.py", line 33, in async_setup_entry
Nov 13 13:28:17 pi3 hass[26493]:     tune = await ngenic.async_tune(tmp_tune.uuid())
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/ngenicpy/models/base.py", line 123, in _async_parse_new_instance
Nov 13 13:28:17 pi3 hass[26493]:     ret_json = self._parse(await self._async_get(url))
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/ngenicpy/models/base.py", line 236, in _async_get
Nov 13 13:28:17 pi3 hass[26493]:     **kwargs)
Nov 13 13:28:17 pi3 hass[26493]:   File "/srv/homeassistant/lib/python3.7/site-packages/ngenicpy/models/base.py", line 177, in _async_request
Nov 13 13:28:17 pi3 hass[26493]:     raise ClientException(self._get_error("A request exception occurred", r, parent_ex=exc))
Nov 13 13:28:17 pi3 hass[26493]: ngenicpy.exceptions.ClientException: (ClientException(...), 'A request exception occurred: ')
```

**Comment by bictorv** [comment]
Which is really odd, since it was running using 0.16 previously. Hmm.

**Comment by sfalkman** [comment]
This shouldn't have anything to do with httpx, you're getting a connection timeout to the ngenic server.
Could you try restarting homeassistant and see if you get it again? I didn't get this issue when updating the component.

**Comment by bictorv** [comment]
Yes, it happens again, but seems intermittent: the first restart, it happens, but the second, it doesn't. Indeed it's a connection timeout, but it could be handled better, perhaps?

**Comment by sfalkman** [comment]
I will look into increasing the timeout and rewriting the handling of connections a bit.

**Comment by sfalkman** [comment]
@bictorv I've made a couple of changes and updated the hass component, please install the latest version and let me know if it works.

**Comment by bictorv** [comment]
Looking good!
